### ISSUE TITLE
Config file refactoring broke the package

### ISSUE THREAD

**Issue by Harvester57** [sourcethemes/academic-admin#21]
Hello :)

Since the changes introduced in https://github.com/gcushen/hugo-academic/commit/ae8a86a04794ce5489b9686957045ef1f70ac859 and given that ther's no config.toml in the root folder anymore, the tool exits with the message

`Please navigate to your website directory (where config.toml resides) and re-run.`

**Comment by Harvester57** [comment]
Oh never mind, the latest commit (https://github.com/sourcethemes/academic-admin/commit/140a7884e8b41d5b1c729352440c3634d400ae9f) seems to be about fixing this issue. when do you plan to push a new package release ? :)

**Comment by Harvester57** [comment]
I backported the changes in the last commit, but it exits with an error:

`AttributeError: 'PosixPath' object has no attribute 'is_folder'`

Arguably, there is no `is_folder` function in Python pathlib module, according to: https://docs.python.org/3/library/pathlib.html, but there is a `is_dir` function that does the trick. I will open a PR with the change :)
